name: 'CDK Destroy'

on:
  workflow_call:
    inputs:
      action:
        type: string
        description: 'CDK Action to Perform'
        required: true
      resource:
        type: string
        description: 'Resource'
        required: true
      app_dir:
        type: string
        description: 'App directory'
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
      AWS_ACCOUNT_ID:
        description: 'AWS Account ID'
        required: true

jobs:
  cdk_apply:
    runs-on: ubuntu-latest
    if: ${{ inputs.action == 'Cdk_destroy' }}
    defaults:
      run:
        working-directory: ${{ inputs.resource }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: ${{ inputs.resource }}/dist
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install dependencies
        run: npm install

      - name: Print working directory
        run: |
          pwd
          ls -al

      - name: Destroy CDK stack
        uses: youyo/aws-cdk-github-actions@v2
        if: ${{ inputs.action == 'Cdk_destroy' }}
        with:
          cdk_subcommand: 'destroy'
          cdk_stack: 'NodejsStack'
          cdk_args: '--require-approval never'
          actions_comment: false
          working_dir: ${{ inputs.resource }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
