name: Deploy Infrastructure
on:
  workflow_dispatch:
    inputs:
      iac_tool:
        type: choice
        description: Choose the IAC tool
        options:
          - terraform
          - cdk
        default: cdk
      # Working directory input from user.
      resource:
        type: choice
        description: Choose the resource
        options:
          - iac/nodejs/
      app_dir:
        type: choice
        description: Choose the app directory
        options:
          - src/nodejs/
      # Terraform action you want to perform
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
          - Terraform_plan
          - Terraform_apply
          - Terraform_destroy

jobs:
  create_app_archives:
    runs-on: ubuntu-latest
    steps:
      - name: Run Create App Archives Workflow
        uses: ./.github/workflows/templates/app/create-app-archives.yml
  terraform_apply:
    name: 'Terraform'
    needs: create_app_archives
    if: ${{ github.event.inputs.action == 'Terraform_plan' || github.event.inputs.action == 'Terraform_apply' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Create App Archives Workflow
        uses: ./.github/workflows/templates/terraform/apply.yml
  terraform_destroy:
    name: 'Terraform_destroy'
    needs: create_app_archives
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Create App Archives Workflow
        uses: ./.github/workflows/templates/terraform/destroy.yml
