name: 'Terrform Destroy'

on:
  workflow_call:
    inputs:
      action:
        type: string
        description: 'Terraform Action to Perform'
        required: true
      resource:
        type: string
        description: 'Resource'
        required: true
      app_dir:
        type: string
        description: 'App directory'
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
      AWS_ACCOUNT_ID:
        description: 'AWS Account ID'
        required: true

jobs:
  terraform_destroy:
    name: 'Terraform_destroy'
    runs-on: ubuntu-latest
    if: ${{ inputs.action == 'Terraform_destroy' }}
    defaults:
      run:
        working-directory: ${{ inputs.resource }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: ${{ github.workspace}}/${{ inputs.app_dir }}/dist
      - name: Print working directory
        run: pwd
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        working-directory: ${{ inputs.resource }}
        run: terraform destroy -auto-approve -var-file=variables.tfvars -var account_id=${{ secrets.AWS_ACCOUNT_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
